name: auto-update

on:
  workflow_call:  # Make it callable from other repos

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Update ALL THE PRS! 🎉
        uses: castastrophe/actions-pr-auto-update@v1.1.0
        with:
          # defaults to github.token
          token: ${{ steps.generate_token.outputs.token }}
          # Optional: include a limit to the number of PRs to update (default is 100)
          limit: 10
          # Optional: set this to true if you want to include draft PRs in those to be updated
          include_drafts: true
          # Optional: include a list of labels which, if present, will prevent the PR from being updated; these are comma-separated.
          exclude_labels: "do not update,skip update"
          # Optional: include a list of labels, at least one of which are required to be present for the PR to be updated; these are comma-separated.
          include_labels: "update,update me"
