name: auto-update

on:
  workflow_call:  # Make it callable from other repos
    inputs:
      repo:
        required: true
        type: string
      owner:
        required: true
        type: string
    secrets:
      GH_APP_ID:
        required: true
      GH_APP_PRIVATE_KEY:
        required: true

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ inputs.owner }}
          repositories: ${{ inputs.repo }}

      - name: Automatically update PR
        uses: adRise/update-pr-branch@v0.10
        with:
          token:  ${{ steps.generate_token.outputs.token }}
          base: 'main'
          required_approval_count: 1
          require_passed_checks: true
          allow_ongoing_checks: true
          sort: 'created'
          direction: 'desc'
          require_auto_merge_enabled: true