name: pre-commit

on:
  workflow_call:  # Make it callable from other repos

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.9 <3.14'
      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch
